# -*- coding: utf-8 -*-
"""Amex

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XjgBzQbhiGpXIuXphT0B2aQiAhKKVYtE

# Amex_CTR

# Importing Libraries
"""

# Commented out IPython magic to ensure Python compatibility.
#for manipulating data
import pandas as pd
import numpy as np

#for the visualization
import matplotlib.pyplot as plt
import seaborn as sns

#for the statistical summary
import math
from scipy import stats

#for the modelling
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

import warnings
warnings.filterwarnings("ignore")
# %pip install xgboost
import xgboost as xgb

# Commented out IPython magic to ensure Python compatibility.
# %pip install optuna

"""# Loading the dataset"""

from google.colab import drive
drive.mount('/content/drive')

import io
dftrain = pd.read_parquet('/content/drive/MyDrive/Amex hackathon/train_data.parquet')

import io
dftest_final = pd.read_parquet('/content/drive/MyDrive/Amex hackathon/test_data (1).parquet')

import io
df_submission = pd.read_csv('/content/685404e30cfdb_submission_template (1).csv')

"""# EDA"""

dftrain.info()

selected_columns = ['f50']  # replace with your column names

for column_name in selected_columns:
    unique_values = dftrain[column_name].unique()
    unique_values_str = ", ".join(map(str, unique_values))

    print(f"Unique values in '{column_name}':\n == {unique_values_str} == \n")
value_counts = dftrain['f50'].value_counts()
print(value_counts)

#Visualization of parameter vs click rate

# Ensure y is numeric
dftrain['y'] = pd.to_numeric(dftrain['y'], errors='coerce')

# Compute click rate including NaNs
click_rates = dftrain.groupby('f42', dropna=False)['y'].mean()

# Replace NaN index with a label for plotting
click_rates.index = click_rates.index.astype(str)
click_rates.rename(index={'nan': 'Missing'}, inplace=True)

# Optional: make NaNs explicit
click_rates = click_rates.rename(index={np.nan: 'Missing'})

# Plot
click_rates.plot(kind='bar')
plt.title("Value Assigned to member")
plt.xlabel("Value of member")
plt.ylabel("Click Rate")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# prompt: i want to see how many unique values are there in f54 and there count give me the code for that

value_counts_f354 = dftrain['f354'].value_counts()
value_counts_f354

dftest.info()

"""#Extra"""

# Calculate the percentage of missing values for each column
missing_percentage = (dftrain.isnull().sum() / len(dftrain)) * 100

# Create a DataFrame to display missing percentages
missing_data = pd.DataFrame({'Column': dftrain.columns, 'Missing Percentage': missing_percentage})

# Remove duplicate column names
missing_data = missing_data.drop_duplicates(subset='Column')

# Sort the DataFrame by missing percentage in descending order
missing_data = missing_data.sort_values(by='Missing Percentage', ascending=True)

# Display the summary
print(missing_data)

# Combine multiple index ranges for categorical
cols_categorical = np.r_[3, 48, 54, 56, 58:63, 355, 360]  # indices 0-2 and 5-6

# Select columns
new_dftrain_categorical = dftrain.iloc[:, cols_categorical]
new_dftrain_categorical.info()

# Check for duplicate rows in the DataFrame
duplicate_rows = dftrain[dftrain.duplicated()]

# Display the duplicate rows, if any
print("Duplicate Rows:")
print(duplicate_rows)

# Remove duplicate rows from the DataFrame
dftrain = dftrain.drop_duplicates()

# Reset the index after removing duplicates
dftrain.reset_index(drop=True, inplace=True)

"""# Data Cleaning

## Train data Cleaning
"""

#creating a copy of train df
#df_clean = dftrain.copy()

# Replace with actual column names to drop
columns_to_drop = ['f135', 'f136', 'f122', 'f112', 'id5']
dftrain.drop(columns=columns_to_drop, inplace=True)

# Convert 'Timestamp' column to datetime format if it's not already
dftrain['id4'] = pd.to_datetime(dftrain['id4'])

# Extract year, month, week, and day into separate columns
dftrain['year_id4'] = dftrain['id4'].dt.year
dftrain['month_id4'] = dftrain['id4'].dt.month
dftrain['week_id4'] = dftrain['id4'].dt.isocalendar().week
dftrain['hour_id4'] = dftrain['id4'].dt.hour
#drop timestamp
dftrain.drop('id4', axis=1, inplace=True)

#frequency encoding the customer_id
dftrain['id2_encoded'] = dftrain['id2'].map(dftrain['id2'].value_counts())
#drop customer_id
dftrain.drop('id2', axis=1, inplace=True)

#frequency encoding the offer_id
dftrain['id3_encoded'] = dftrain['id3'].map(dftrain['id3'].value_counts())

#drop customer_id
dftrain.drop('id3', axis=1, inplace=True)

#ordinal mapping of f42(membership level)
# Define the ordinal mapping
membership_mapping = {
    'none': 0,
    'R': 1,   # Red
    'G': 2,   # Gold
    'P': 3,   # Platinum
    'S': 4    # Signature / Sapphire
}

# Apply the mapping to the column f42
dftrain['f42_encoded'] = dftrain['f42'].map(membership_mapping)

# Fill NaN with -1 to retain missingness as a signal
dftrain['f42_encoded'].fillna(-1, inplace=True)

# drop the original column
dftrain.drop(columns=['f42'], inplace=True)

# f48 already encoded

# ordinal encoding for f50
# Create a mapping dictionary
account_mapping = {
    'Y': 1,
    'N': 0
}

# Apply the mapping
dftrain['f50_encoded'] = dftrain['f50'].map(account_mapping)

# Fill NaN with -1 to retain missingness as a signal
dftrain['f50_encoded'].fillna(-1, inplace=True)

# drop the original column
dftrain.drop(columns=['f50'], inplace=True)

# ordinal encoding for f52
# Create a mapping dictionary
account_mapping = {
    'Y': 1,
    'N': 0
}

# Apply the mapping
dftrain['f52_encoded'] = dftrain['f52'].map(account_mapping)

# Fill NaN with -1 to retain missingness as a signal
dftrain['f52_encoded'].fillna(-1, inplace=True)

# drop the original column
dftrain.drop(columns=['f52'], inplace=True)

# ordinal encoding for f53
# Create a mapping dictionary
account_mapping = {
    'NN': 1,
    'NY': 0
}

# Apply the mapping
dftrain['f53_encoded'] = dftrain['f53'].map(account_mapping)

# Fill NaN with -1 to retain missingness as a signal
dftrain['f53_encoded'].fillna(-1, inplace=True)

# drop the original column
dftrain.drop(columns=['f53'], inplace=True)

# prompt: i want to convert this categorical value into numerical with A having the highest priority and F having the lowest

# Ordinal mapping for 'f54'
f54_mapping = {
    'A': 5,
    'B': 4,
    'C': 3,
    'D': 2,
    'E': 1,
    'F': 0
}

# Apply the mapping to the column f54
dftrain['f54_encoded'] = dftrain['f54'].map(f54_mapping)

# Fill NaN with a value that represents missingness if needed
# For example, filling with -1 or a different strategy like median/mode imputation if appropriate
dftrain['f54_encoded'].fillna(-1, inplace=True) # Or use a different strategy like median/mode imputation if appropriate

# drop the original column
dftrain.drop(columns=['f54'], inplace=True)

#encoding f55

# Overall click rate
global_mean = dftrain['y'].mean()  # ≈ 0.05

# Smoothing parameter
k = 300  # You can tune this

# Calculate category-wise click rate and count
agg = dftrain.groupby('f55')['y'].agg(['mean', 'count'])
agg['smoothed'] = (agg['count'] * agg['mean'] + k * global_mean) / (agg['count'] + k)

# Create mapping from category to smoothed value
encoding_map55 = agg['smoothed'].to_dict()

# Fill '-' and NaN manually if needed
encoding_map55['-'] = global_mean
encoding_map55[np.nan] = global_mean

# Apply encoding
dftrain['f55_encoded'] = dftrain['f55'].map(encoding_map55).fillna(global_mean)

# drop the original column
dftrain.drop(columns=['f55'], inplace=True)

#encoding f56

# Overall click rate
global_mean = dftrain['y'].mean()  # ≈ 0.05

# Smoothing parameter
k = 300  # You can tune this

# Calculate category-wise click rate and count
agg = dftrain.groupby('f56')['y'].agg(['mean', 'count'])
agg['smoothed'] = (agg['count'] * agg['mean'] + k * global_mean) / (agg['count'] + k)

# Create mapping from category to smoothed value
encoding_map56 = agg['smoothed'].to_dict()

# Fill '-' and NaN manually if needed
encoding_map56['-'] = global_mean
encoding_map56[np.nan] = global_mean

# Apply encoding
dftrain['f56_encoded'] = dftrain['f56'].map(encoding_map56).fillna(global_mean)

# drop the original column
dftrain.drop(columns=['f56'], inplace=True)

#encoding f57

# Overall click rate
global_mean = dftrain['y'].mean()  # ≈ 0.05

# Smoothing parameter
k = 300  # You can tune this

# Calculate category-wise click rate and count
agg = dftrain.groupby('f57')['y'].agg(['mean', 'count'])
agg['smoothed'] = (agg['count'] * agg['mean'] + k * global_mean) / (agg['count'] + k)

# Create mapping from category to smoothed value
encoding_map57 = agg['smoothed'].to_dict()

# Fill '-' and NaN manually if needed
encoding_map57['-'] = global_mean
encoding_map57[np.nan] = global_mean

# Apply encoding
dftrain['f57_encoded'] = dftrain['f57'].map(encoding_map57).fillna(global_mean)

# drop the original column
dftrain.drop(columns=['f57'], inplace=True)

#encoding f349

# One-hot encode the 'weekday' column
df_onehot = pd.get_dummies(dftrain['f349'], prefix='f349_encoded')

# Combine with original DataFrame if needed
df = pd.concat([dftrain, df_onehot], axis=1)

# drop the original column
dftrain.drop(columns=['f349'], inplace=True)

#encoding f354

# Overall click rate
global_mean = dftrain['y'].mean()  # ≈ 0.05

# Smoothing parameter
k = 300  # You can tune this

# Calculate category-wise click rate and count
agg = dftrain.groupby('f354')['y'].agg(['mean', 'count'])
agg['smoothed'] = (agg['count'] * agg['mean'] + k * global_mean) / (agg['count'] + k)

# Create mapping from category to smoothed value
encoding_map354 = agg['smoothed'].to_dict()

# Fill '-' and NaN manually if needed
encoding_map354['-'] = global_mean
encoding_map354[np.nan] = global_mean

# Apply encoding
dftrain['f354_encoded'] = dftrain['f354'].map(encoding_map354).fillna(global_mean)

# drop the original column
dftrain.drop(columns=['f354'], inplace=True)

"""## Test data Cleaning"""

#creating a copy of train df
#df_clean = dftrain.copy()

# Replace with actual column names to drop
columns_to_drop = ['f135', 'f136', 'f122', 'f112', 'id5']
dftest_final.drop(columns=columns_to_drop, inplace=True)

# Convert 'Timestamp' column to datetime format if it's not already
dftest_final['id4'] = pd.to_datetime(dftest_final['id4'])

# Extract year, month, week, and day into separate columns
dftest_final['year_id4'] = dftest_final['id4'].dt.year
dftest_final['month_id4'] = dftest_final['id4'].dt.month
dftest_final['week_id4'] = dftest_final['id4'].dt.isocalendar().week
dftest_final['hour_id4'] = dftest_final['id4'].dt.hour
#drop timestamp
dftest_final.drop('id4', axis=1, inplace=True)

#frequency encoding the customer_id
dftest_final['id2_encoded'] = dftest_final['id2'].map(dftest_final['id2'].value_counts())
#drop customer_id
dftest_final.drop('id2', axis=1, inplace=True)

#frequency encoding the offer_id
dftest_final['id3_encoded'] = dftest_final['id3'].map(dftest_final['id3'].value_counts())
#drop customer_id
dftest_final.drop('id3', axis=1, inplace=True)

#ordinal mapping of f42(membership level)
# Define the ordinal mapping
membership_mapping = {
    'none': 0,
    'R': 1,   # Red
    'G': 2,   # Gold
    'P': 3,   # Platinum
    'S': 4    # Signature / Sapphire
}

# Apply the mapping to the column f42
dftest_final['f42_encoded'] = dftest_final['f42'].map(membership_mapping)

# Fill NaN with -1 to retain missingness as a signal
dftest_final['f42_encoded'].fillna(-1, inplace=True)

# drop the original column
dftest_final.drop(columns=['f42'], inplace=True)

# f48 already encoded

# ordinal encoding for f50
# Create a mapping dictionary
account_mapping = {
    'Y': 1,
    'N': 0
}

# Apply the mapping
dftest_final['f50_encoded'] = dftest_final['f50'].map(account_mapping)

# Fill NaN with -1 to retain missingness as a signal
dftest_final['f50_encoded'].fillna(-1, inplace=True)

# drop the original column
dftest_final.drop(columns=['f50'], inplace=True)

# ordinal encoding for f52
# Create a mapping dictionary
account_mapping = {
    'Y': 1,
    'N': 0
}

# Apply the mapping
dftest_final['f52_encoded'] = dftest_final['f52'].map(account_mapping)

# Fill NaN with -1 to retain missingness as a signal
dftest_final['f52_encoded'].fillna(-1, inplace=True)

# drop the original column
dftest_final.drop(columns=['f52'], inplace=True)

# ordinal encoding for f53
# Create a mapping dictionary
account_mapping = {
    'NN': 1,
    'NY': 0
}

# Apply the mapping
dftest_final['f53_encoded'] = dftest_final['f53'].map(account_mapping)

# Fill NaN with -1 to retain missingness as a signal
dftest_final['f53_encoded'].fillna(-1, inplace=True)

# drop the original column
dftest_final.drop(columns=['f53'], inplace=True)

# prompt: i want to convert this categorical value into numerical with A having the highest priority and F having the lowest

# Ordinal mapping for 'f54'
f54_mapping = {
    'A': 5,
    'B': 4,
    'C': 3,
    'D': 2,
    'E': 1,
    'F': 0
}

# Apply the mapping to the column f54
dftest_final['f54_encoded'] = dftest_final['f54'].map(f54_mapping)

# Fill NaN with a value that represents missingness if needed
# For example, filling with -1 or a different strategy like median/mode imputation if appropriate
dftest_final['f54_encoded'].fillna(-1, inplace=True) # Or use a different strategy like median/mode imputation if appropriate

# drop the original column
dftest_final.drop(columns=['f54'], inplace=True)

#encoding f55

# Apply encoding
dftest_final['f55_encoded'] = dftest_final['f55'].map(encoding_map55).fillna(global_mean)

# drop the original column
dftest_final.drop(columns=['f55'], inplace=True)

#encoding f56



# Apply encoding
dftest_final['f56_encoded'] = dftest_final['f56'].map(encoding_map56).fillna(global_mean)

# drop the original column
dftest_final.drop(columns=['f56'], inplace=True)

#encoding f57

# Apply encoding
dftest_final['f57_encoded'] = dftest_final['f57'].map(encoding_map57).fillna(global_mean)

# drop the original column
dftest_final.drop(columns=['f57'], inplace=True)

#encoding f349

# One-hot encode the 'weekday' column
df_onehot = pd.get_dummies(dftest_final['f349'], prefix='f349_encoded')

# Combine with original DataFrame if needed
df = pd.concat([dftest_final, df_onehot], axis=1)

# drop the original column
dftest_final.drop(columns=['f349'], inplace=True)

#encoding f354

# Apply encoding
dftest_final['f354_encoded'] = dftest_final['f354'].map(encoding_map354).fillna(global_mean)

# drop the original column
dftest_final.drop(columns=['f354'], inplace=True)

dftest_final.info()

"""# Training the Model"""

from sklearn.preprocessing import OrdinalEncoder

# 1. Copy the original dataframe to avoid modifying it in-place
df_num = dftrain.copy()
# Replace with actual column names to drop
columns_to_drop = ['id1']
df_num.drop(columns=columns_to_drop, inplace=True)

# 2. Identify numeric and categorical columns
num_cols = df_num.select_dtypes(include=['number']).columns
cat_cols = df_num.select_dtypes(include=['object', 'category']).columns

# 3. Convert categorical columns using OrdinalEncoder, preserving NaNs
ordinal_encoder = OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1, encoded_missing_value=float('nan'))
df_num[cat_cols] = ordinal_encoder.fit_transform(df_num[cat_cols].astype(str).where(df_num[cat_cols].notnull()))

# ✅ Now df_num is fully numeric, with NaNs preserved

df_num

X = df_num.drop('y', axis=1)  # Features
y = df_num['y']               # Target

X_train, X_temp, y_train, y_temp = train_test_split(
    X, y,                # These come from Step 3
    test_size=0.3,       # 30% for testing, 70% for training
    random_state=42      # Ensures reproducibility
)

# Then split temp into validation + test
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)

#only for optuna
X_train, X_test, y_train, y_test = train_test_split(
    X, y,                # These come from Step 3
    test_size=0.2,       # 20% for testing, 70% for training
    random_state=42      # Ensures reproducibility
)

from sklearn.metrics import roc_auc_score, log_loss

# X_train, y_train, X_val, y_val, X_test, y_test assumed to be pre-defined

# 1. Create DMatrix (optional but recommended for efficiency)
dtrain_final = xgb.DMatrix(X_train, label=y_train)
dval   = xgb.DMatrix(X_val, label=y_val)
dtest  = xgb.DMatrix(X_test)

# 2. Define model parameters for binary classification
params = {
    'objective': 'binary:logistic',  # output between 0 and 1
    'eval_metric': 'logloss',
    'learning_rate': 0.062129403461308894, 'max_depth': 7, 'min_child_weight': 6, 'subsample': 0.8927292439779493, 'colsample_bytree': 0.8315387407529795
}

# 3. Training with early stopping on validation set
watchlist = [(dtrain_final, 'train'), (dval, 'eval')]

model = xgb.train(
    params=params,
    dtrain=dtrain_final,
    num_boost_round=1000,
    evals=watchlist,
    early_stopping_rounds=30,
    verbose_eval=10
)

# 4. Predict probabilities on test set
y_pred_proba = model.predict(dtest)  # Outputs probabilities between 0 and 1

# 5. Evaluate on validation or test set (optional)
val_pred_proba = model.predict(dval)
print("Validation Log Loss:", log_loss(y_val, val_pred_proba))
print("Validation ROC AUC:", roc_auc_score(y_val, val_pred_proba))

# 6. Save predictions
output = pd.DataFrame({
    'predicted_probability': y_pred_proba
})
print(output.head())



import optuna
from sklearn.model_selection import train_test_split

def objective(trial):
    param = {
        'objective': 'binary:logistic',
        'eval_metric': 'logloss',
        'tree_method': 'hist',
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3),
        'max_depth': trial.suggest_int('max_depth', 3, 10),
        'min_child_weight': trial.suggest_int('min_child_weight', 1, 10),
        'subsample': trial.suggest_float('subsample', 0.6, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.6, 1.0),
    }

    dtrain = xgb.DMatrix(X_train, label=y_train)

    cv_results = xgb.cv(
        params=param,
        dtrain=dtrain,
        num_boost_round=1000,
        nfold=3,
        early_stopping_rounds=30,
        stratified=True,
        verbose_eval=False
    )

    return cv_results['test-logloss-mean'].min()

study = optuna.create_study(direction='minimize')
study.optimize(objective, n_trials=30)

print("✅ Best parameters:", study.best_params)
print("📉 Best logloss:", study.best_value)

# 5. Evaluate on validation or test set (optional)
test_pred_proba = model.predict(dtest)
print("Validation Log Loss:", log_loss(y_test, test_pred_proba))
print("Validation ROC AUC:", roc_auc_score(y_test, test_pred_proba))

from sklearn.preprocessing import OrdinalEncoder

# 1. Copy the original dataframe to avoid modifying it in-place
dfnum_test = dftest_final.copy()
# Replace with actual column names to drop
columns_to_drop = ['id1']
dfnum_test.drop(columns=columns_to_drop, inplace=True)

# 2. Identify numeric and categorical columns
num_cols = dfnum_test.select_dtypes(include=['number']).columns
cat_cols = dfnum_test.select_dtypes(include=['object', 'category']).columns

# 3. Convert categorical columns using OrdinalEncoder, preserving NaNs
ordinal_encoder = OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1, encoded_missing_value=float('nan'))
dfnum_test[cat_cols] = ordinal_encoder.fit_transform(dfnum_test[cat_cols].astype(str).where(dfnum_test[cat_cols].notnull()))

# ✅ Now dfnum_test is fully numeric, with NaNs preserved

dtest_final = xgb.DMatrix(dfnum_test)
y_pred_proba_final = model.predict(dtest_final)

y_pred_proba_final.info()

columns_to_drop = ['pred']
df_submission.drop(columns=columns_to_drop, inplace=True)

dftest_final['pred'] = y_pred_proba_final

# Merge on 'id1' to bring in 'pred' column
df_merged_submission = pd.merge(df_submission, dftest_final[['id1', 'pred']], on='id1', how='left')

df_merged_submission

# prompt: i want to download df_merged_submission in csv

from google.colab import files

df_merged_submission.to_csv('df_merged_submission.csv', index=False)
files.download('df_merged_submission.csv')